version: '3.8'

services:
  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - AUTH_API=http://authentication:4001
      - COURSE_API=http://course:4002
      - LEARNER_API=http://learner:4003
      - PAYMENT_API=http://payment:4004
    networks:
      - app-network

  authentication:
    build:
      context: ./authentication-microservice
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    networks:
      - app-network
    
  course:
    build:
      context: ./course-microservice
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    networks:
      - app-network

  learner:
    build:
      context: ./learner-microservice
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    networks:
      - app-network

  payment:
    build:
      context: ./payment-microservice
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
