
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  type: ClusterIP
  selector:
    app: course
  ports:
    - port: 4003
      targetPort: 4003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: ardpeiris/ctse-course:latest
          ports:
            - containerPort: 4003
          env:
            - name: API_GATEWAY_PORT
              value: "4000"
            - name: AUTH_PORT
              value: "4001"
            - name: LEARNER_PORT
              value: "4002"
            - name: COURSE_PORT
              value: "4003"
            - name: PAYMENT_PORT
              value: "4004"
            - name: MONGO_URI
              value: "mongodb+srv://admin:admin@ctse.jek3a.mongodb.net/?retryWrites=true&w=majority&appName=ctse"
            - name: AUTH_API
              value: "http://authentication:4001"
            - name: LEARNER_API
              value: "http://learner:4002"
            - name: COURSE_API
              value: "http://course:4003"
            - name: PAYMENT_API
              value: "http://payment:4004"
            - name: JWT_SECRET
              value: "secret"